---
driver_plugin: docker
busser:
  sudo: true

platforms:
- name: centos-6.4
  driver_config:
    image: centos:6.4 
    platform: centos

suites:
- name: default
  run_list: 
    - "recipe[timezone::default]"
  attributes: {}
